# This is a basic workflow to help you get started with Actions

name: Build / Test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main
  pull_request:
    branches:
     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: |
          npm ci
      - name: Build Production
        run: |
          npm run build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: |
          npm ci
      - name: Test
        run: |
          npm run test:unit
